name: teatime
version: "20.06"
confinement: strict
grade: stable
summary: Simple egg timer application for the Unity Desktop
description:  A simple egg-timer type application to time your teas. 
 Rings an alarm and displays an desktop notification, when the tea is ready. 
 Supports saving several pre-set timers.
base: core18

apps:
  teatime:
    command: teatime.py
    plugs: [unity7, pulseaudio]
    extensions: [gnome-3-28]
    environment:
      PYTHONPATH: $SNAP/gnome-platform/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3/dist-packages

slots:
  # for GtkApplication registration
  teatime:
    interface: dbus
    bus: session
    name: net.rojtberg.teatime

parts:
    teatime:
        plugin: python
        source: .
        build-packages:
            - gcc # workaround for gnome-3-28
        stage-packages:
            - python3-distutils-extra
            - gir1.2-unity-5.0
            - gir1.2-notify-0.7
        stage:
            # clutter pulled by distutils extra
            - -usr/share/perl
            - -usr/lib/*/perl
    cleanup:
      after:  [teatime]
      plugin: nil
      build-snaps:
        - core18
        - gnome-3-28-1804
      override-prime: |
        set -eux
        for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
            cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
        done
