name: teatime
version: 18.02
confinement: strict
grade: stable
summary: Simple egg timer application for the Unity Desktop
description:  A simple egg-timer type application to time your teas. 
 Rings an alarm and displays an desktop notification, when the tea is ready. 
 Supports saving several pre-set timers.

apps:
  teatime:
    command: desktop-launch $SNAP/share/teatime/teatime.py
    plugs: [unity7, home, pulseaudio]

slots:
  # for GtkApplication registration
  teatime:
    interface: dbus
    bus: session
    name: net.rojtberg.teatime

parts:
    teatime:
        plugin: python
        source: git://git.launchpad.net/teatime
        stage-packages:
            - python3-distutils-extra
            - sound-theme-freedesktop
            - pulseaudio-utils
            - python3-gi
            - gir1.2-unity-5.0
            - gir1.2-notify-0.7
            - gir1.2-gtk-3.0
            - gir1.2-pango-1.0
        after: [desktop-gtk3]
        stage:
            - -usr/share/pkgconfig # also in desktop-gtk3
            - -usr/share/mime      # also in desktop-gtk3
